services:
  postgres:
    image: postgres:17.5-alpine3.21
    ports:
      - "15432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - "./temp_files/postgresql_data:/var/lib/postgresql/data"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./electra_back
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./config.yaml:/app/config.yaml

  frontend:
    build: ./electra_front
    ports:
      - "3000:3000"
    depends_on:
      - backend
